### ISSUE TITLE
Is it possible to not require loading arca before models?

### ISSUE THREAD

**Issue by jch** [jonmagic/arca#14]
From the [rails docs](http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html):

> Debugging callbacks
> 
> The callback chain is accessible via the _*_callbacks method on an object. ActiveModel Callbacks support :before, :after and :around as values for the kind property. The kind property defines what part of the chain the callback runs in.
> 
> To find all callbacks in the before_save callback chain:

``` ruby
Topic._save_callbacks.select { |cb| cb.kind.eql?(:before) }
Returns an array of callback objects that form the before_save chain.
```

> To further check if the before_save chain contains a proc defined as rest_when_dead use the filter property of the callback object:

``` ruby
Topic._save_callbacks.select { |cb| cb.kind.eql?(:before) }.collect(&:filter).include?(:rest_when_dead)
```

> Returns true or false depending on whether the proc is contained in the before_save callback chain on a Topic model.

Is it possible to use these hooks to do reporting? This would remove the requirement that arca loads before everything.

**Comment by jonmagic** [comment]
> Is it possible to use these hooks to do reporting? This would remove the requirement that arca loads before everything.

I did try that route when developing Arca but I couldn't get all of the file and line number based reporting.

**Comment by jch** [comment]
Seems like a good opportunity to push it upstream to active_record :wink:

Feel free to close. I was just curious.

**Comment by jonmagic** [comment]
> Seems like a good opportunity to push it upstream to active_record

Maybe someday :) As far as I know there isn't anything similar in rails (reporting file and line number for method calls and storing those on an object somewhere for analysis).

**Comment by jch** [comment]
When I was looking, the callbacks were defined with class eval meta programming. I think it's possible for ar to store that information, but you're right, "someday" is probably right.
